sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
  - '10'
  - '12'
script:
  - npm start validate
  - npx codecov
jobs:
  include:
    - stage: release
      node_js: "lts/*"
      script:
        - npm start build
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release@15
branches:
  only:
    - master
